### ISSUE TITLE
When token is revoked, removing a client doesn't stop it from trying to reconnect

### ISSUE THREAD

**Issue by louis6321** [CataIana/twitchcommandbot#2]
![XfsuZY7Srd](https://user-images.githubusercontent.com/43100308/167544986-340c1c4d-36c4-4db1-8232-a216ef7f888a.png)
![Discord_WU9N84aoA8](https://user-images.githubusercontent.com/43100308/167544990-d8199c62-2210-4455-bf17-7b9501feed06.png)

**Comment by CataIana** [comment]
This should be fixed in the latest commit

**Comment by louis6321** [comment]
Fixed, thanks!
